[general]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
size = 14

[font.bold]
family = "ComicCodeLigatures Nerd Font"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal]
shell = "fish"

[window.dimensions]
columns = 150
lines = 60

[window.padding]
x = 15
y = 10

# Colors (Dracula)
[colors.primary]
background=        "#0d0d0d"
foreground=        "#f8f8f2"
dim_foreground=    "#cdd6f4"
bright_foreground= "#cdd6f4"

[colors.normal]
black=   '#100e23'
red=     '#ff5555'
green=   '#50fa7b'
yellow=  '#fff7b7'
blue=    '#43b7ff'
magenta= '#ff92df'
cyan=    '#aaffe4'
white=   '#f8f8f2'

[colors.bright]
black=   '#686868'
red=     '#ff6e6e'
green=   '#69ff94'
yellow=  '#ffff80'
blue=    '#00cfff'
magenta= '#ff79c6'
cyan=    '#7cfffe'
white=   '#ffffff'

